import type { Project, ProjectImage } from "@/types/content";

/** Build image entries from `/public/projects/<slug>/<file>.webp`. */
function screens(
  slug: string,
  title: string,
  items: [file: string, caption: string, orientation?: "portrait"][],
): ProjectImage[] {
  return items.map(([file, caption, orientation]) => ({
    src: `/projects/${slug}/${file}.webp`,
    alt: `${title} — ${caption} screen`,
    caption,
    orientation: orientation ?? "landscape",
  }));
}

export const projects: Project[] = [
  {
    slug: "lwazi-hair",
    title: "Lwazi Hair",
    industry: "E-commerce / Shopify",
    category: "Client",
    status: "Live · client project",
    tagline:
      "A live Shopify store for a South African human-hair and wig retailer — built end to end and shipping real orders.",
    overview:
      "Designed and built the full Shopify storefront for Lwazi Hair, a human-hair and wig retailer trading online and wholesale. Beyond a standard theme setup, the store runs a custom multi-step product configurator — customers choose length, texture and colour and see the price update live before adding to cart — wired into Yoco for secure card payments and a one-tap WhatsApp flow for order enquiries.",
    features: [
      "Custom multi-step wig configurator (length, texture, colour, add-on customisation)",
      "Live price recalculation as customers change options, before checkout",
      "85+ products merchandised across wigs, bundles, closures and frontals",
      "Secure checkout with Yoco card payments and full order summary",
      "Cart reservation confirmation flow to reduce checkout drop-off",
      "One-tap WhatsApp click-to-order integration for direct customer support",
    ],
    contributions: [
      "Designed and built the complete storefront and theme customisations in Liquid and JavaScript",
      "Engineered the configurator and live-pricing logic on the product page",
      "Integrated Yoco payments and the WhatsApp Business ordering flow",
      "Merchandised and structured the 85+ product catalogue for discoverability",
    ],
    stack: ["Shopify", "Liquid", "JavaScript", "Yoco Payments", "WhatsApp Business"],
    skills: ["E-commerce UX", "Product configurators", "Payments integration", "Client delivery"],
    accent: "rose",
    featured: true,
    images: screens("lwazi-hair", "Lwazi Hair", [
      ["01-storefront", "Storefront"],
      ["02-wig-configurator", "Wig configurator"],
      ["03-live-pricing", "Live pricing & checkout"],
    ]),
  },
  {
    slug: "financeflow",
    title: "FinanceFlow",
    industry: "Financial Services",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A secure, responsive dashboard for accounts, transfers and reporting.",
    overview:
      "FinanceFlow is a responsive financial services dashboard for account balances, transaction history, transfers, and beneficiary management. It was built around secure authentication flows, idempotent transaction requests, defensive error handling, and an audit trail, so customers and support staff can trust every balance and transfer shown on screen.",
    features: [
      "Real-time account balance and transaction history views with drill-down detail",
      "Money transfer workflow with beneficiary management and confirmation steps",
      "Idempotent transaction requests to prevent duplicate transfers on retry or network failure",
      "Form validation and defensive error handling across every money-movement flow",
      "Audit event log for transfers and account changes to support compliance reviews",
      "API-driven reporting views for account activity, exportable for reconciliation",
    ],
    contributions: [
      "Designed the React/TypeScript front end and the Next.js routing and data-fetching layer",
      "Built the Node.js REST API and PostgreSQL schema for accounts, transfers and audit events",
      "Implemented idempotency keys and validation on the transfer endpoints to protect data integrity",
      "Set up GitHub Actions for linting, automated tests and CI checks on every pull request",
    ],
    stack: ["React", "TypeScript", "Next.js", "Node.js", "PostgreSQL", "Tailwind CSS", "GitHub Actions"],
    skills: ["Secure authentication", "REST API design", "PostgreSQL schema design", "CI/CD", "Form validation"],
    accent: "blue",
    featured: true,
    caseStudyPdf: "/docs/financeflow-case-study.pdf",
    images: screens("financeflow", "FinanceFlow", [
      ["01-overview", "Overview"],
      ["02-transactions", "Transactions"],
      ["03-new-transfer", "New transfer"],
      ["04-audit-log", "Audit log"],
      ["05-beneficiaries", "Beneficiaries"],
      ["06-reports", "Reports"],
    ]),
  },
  {
    slug: "shopsphere",
    title: "ShopSphere",
    industry: "E-commerce",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A full-stack storefront with catalogue, cart and order management.",
    overview:
      "ShopSphere is a full-stack commerce application covering the product catalogue, search and filtering, cart management, checkout, customer accounts and order history. The interface is mobile-first and the backend exposes inventory-aware APIs so stock levels stay accurate across browsing, checkout and fulfilment.",
    features: [
      "Product catalogue with search, category filters and sort options",
      "Cart and multi-step checkout workflow with order summary and validation",
      "Customer account area with saved addresses and order history",
      "Inventory-aware APIs that keep stock counts accurate through checkout",
      "Responsive, mobile-first layouts across catalogue, product and checkout pages",
      "Deployed on Vercel with a MongoDB-backed product and order data model",
    ],
    contributions: [
      "Built the catalogue, product detail and checkout flows in React/Next.js and TypeScript",
      "Designed the MongoDB schema for products, inventory, carts and orders",
      "Implemented the Node.js order and inventory APIs, including stock-decrement logic",
      "Tuned layouts and Tailwind CSS breakpoints for a mobile-first shopping experience",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "MongoDB", "Tailwind CSS", "Vercel"],
    skills: ["E-commerce UX", "MongoDB data modelling", "API design", "Mobile-first UI"],
    accent: "amber",
    featured: true,
    caseStudyPdf: "/docs/shopsphere-case-study.pdf",
    images: screens("shopsphere", "ShopSphere", [
      ["01-storefront", "Storefront"],
      ["02-product-detail", "Product detail"],
      ["03-cart-checkout", "Cart & checkout"],
      ["04-order-history", "Order history"],
      ["05-search-filters", "Search & filters"],
      ["06-order-confirmation", "Order confirmation"],
    ]),
  },
  {
    slug: "fleetflow",
    title: "FleetFlow",
    industry: "Logistics & Field Ops",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A live operations dashboard for dispatch, field workers and tasks.",
    overview:
      "FleetFlow is an operations dashboard for dispatching work, tracking driver and field-worker activity, and monitoring task status in real time. Location updates and status changes stream over WebSockets so dispatchers always see current, not stale, field data.",
    features: [
      "Live dispatch board for assigning tasks to drivers and field workers",
      "Real-time location and status updates over WebSockets",
      "Task status tracking from assigned through in-progress to completed",
      "Operational reporting on completion rates and response times",
      "Map-oriented views for field-worker location and route context",
    ],
    contributions: [
      "Built the real-time dispatch UI in React/TypeScript with live WebSocket updates",
      "Designed the PostgreSQL schema for tasks, drivers and status history",
      "Implemented the Node.js WebSocket layer for location and status broadcast",
      "Deployed the service on AWS and set up monitoring for the real-time connections",
    ],
    stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "WebSockets", "AWS"],
    skills: ["Real-time systems", "Operational dashboards", "PostgreSQL", "AWS deployment"],
    accent: "cyan",
    caseStudyPdf: "/docs/fleetflow-case-study.pdf",
    images: screens("fleetflow", "FleetFlow", [
      ["01-live-map", "Live dispatch map"],
      ["02-task-board", "Task board"],
      ["03-drivers", "Drivers"],
      ["04-task-detail", "Task detail"],
      ["05-reports", "Reports"],
      ["06-new-task", "New task"],
    ]),
  },
  {
    slug: "learnhub",
    title: "LearnHub",
    industry: "Education / EdTech",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A learning platform for courses, progress tracking and assessments.",
    overview:
      "LearnHub is a learning platform covering course discovery, lessons, progress tracking, assessments and learner dashboards, alongside instructor tools for managing content. The interface was built with accessibility and responsiveness as first-class requirements.",
    features: [
      "Course discovery and enrolment with category and level filtering",
      "Lesson player with progress tracking across modules",
      "Assessments and quizzes with score history",
      "Learner dashboard summarising progress across active courses",
      "Instructor content-management views for courses and lessons",
      "Accessibility-focused, responsive layouts throughout",
    ],
    contributions: [
      "Built the learner and instructor dashboards in React/Next.js and TypeScript",
      "Designed the PostgreSQL schema for courses, lessons, enrolments and progress",
      "Implemented progress-tracking and assessment-scoring APIs in Node.js",
      "Audited and improved keyboard navigation and accessibility across key flows",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    skills: ["Accessibility (a11y)", "Progress-tracking systems", "PostgreSQL", "Responsive UI"],
    accent: "green",
    caseStudyPdf: "/docs/learnhub-case-study.pdf",
    images: screens("learnhub", "LearnHub", [
      ["01-catalogue", "Course catalogue"],
      ["02-lesson-player", "Lesson player"],
      ["03-learner-dashboard", "Learner dashboard"],
      ["04-learners", "Learners"],
      ["05-assessment", "Assessment"],
      ["06-course-landing", "Course landing page"],
    ]),
  },
  {
    slug: "propmanage",
    title: "PropManage",
    industry: "Real Estate / PropTech",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A property management app for listings, tenants and maintenance.",
    overview:
      "PropManage is a property management application for listings, tenant records, maintenance requests and document workflows. Role-based access keeps agents, property managers and administrators scoped to the data relevant to their role.",
    features: [
      "Property listing management with search and filtering",
      "Tenant records and lease tracking",
      "Maintenance request workflow from submission through resolution",
      "Document workflows for leases and inspection reports",
      "Role-based access control across agents, managers and admins",
      "Dashboards summarising occupancy and open maintenance items",
    ],
    contributions: [
      "Built the listings, tenant and maintenance-request UIs in React/TypeScript",
      "Designed the Express.js REST API and MongoDB schema for properties, leases and tickets",
      "Implemented role-based access control across the API and front end",
      "Set up document upload and storage workflows on AWS",
    ],
    stack: ["React", "TypeScript", "Node.js", "Express.js", "MongoDB", "AWS"],
    skills: ["Role-based access control", "Express.js API design", "MongoDB", "AWS document storage"],
    accent: "purple",
    caseStudyPdf: "/docs/propmanage-case-study.pdf",
    images: screens("propmanage", "PropManage", [
      ["01-listings", "Listings grid"],
      ["02-property-detail", "Property detail"],
      ["03-maintenance", "Maintenance board"],
      ["04-tenants", "Tenants"],
      ["05-new-maintenance-request", "New maintenance request"],
      ["06-documents", "Documents"],
    ]),
  },
  {
    slug: "talenthub",
    title: "TalentHub",
    industry: "HR / People Ops",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A recruitment and employee-management workflow tool.",
    overview:
      "TalentHub is a recruitment and employee-management interface covering vacancies, candidate pipelines, interview scheduling, onboarding tasks and employee records, with permissioned access for HR, hiring managers and administrators.",
    features: [
      "Vacancy management with candidate pipeline stages",
      "Interview scheduling with calendar-style views",
      "Onboarding task checklists for new hires",
      "Employee records with permissioned, role-based visibility",
      "Workflow dashboards summarising pipeline health across open roles",
    ],
    contributions: [
      "Built the candidate pipeline and interview-scheduling UI in React/Next.js and TypeScript",
      "Designed the PostgreSQL schema for vacancies, candidates, interviews and onboarding tasks",
      "Implemented permissioned employee-record views in the Node.js API",
      "Configured GitHub Actions for automated testing and deployment checks",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "GitHub Actions"],
    skills: ["Workflow / pipeline UI", "PostgreSQL schema design", "Access control", "CI/CD"],
    accent: "blue",
    caseStudyPdf: "/docs/talenthub-case-study.pdf",
    images: screens("talenthub", "TalentHub", [
      ["01-pipeline", "Candidate pipeline"],
      ["02-candidate-profile", "Candidate profile"],
      ["03-interview-calendar", "Interview calendar"],
      ["04-vacancies", "Vacancies"],
      ["05-new-vacancy", "New vacancy"],
      ["06-employees", "Employee directory"],
    ]),
  },
  {
    slug: "knights-nestle",
    title: "Knights-Nestle Management System",
    industry: "Retail Operations",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A merchandiser scheduling and stock-reporting tool for retail execution.",
    overview:
      "A full-stack retail execution application for scheduling and tracking distributed merchandiser workflows and stock reports, built with mobile-responsive React interfaces so field merchandisers can log visits and stock counts from any device.",
    features: [
      "Merchandiser visit scheduling across multiple retail stores",
      "In-store stock-report capture from mobile-responsive screens",
      "Visit status and stock-compliance tracking",
      "Manager-facing dashboards summarising visit and compliance rates",
    ],
    contributions: [
      "Built the merchandiser scheduling and stock-reporting UI in React",
      "Implemented the Node.js API for visit scheduling and stock-report submission",
      "Optimised layouts for in-store mobile use, since merchandisers work primarily on phones",
    ],
    stack: ["React", "Node.js", "Responsive UI"],
    skills: ["Mobile-responsive UI", "Field-operations tooling", "Node.js API design"],
    accent: "green",
    caseStudyPdf: "/docs/knights-nestle-case-study.pdf",
    images: screens("knights-nestle", "Knights-Nestle", [
      ["01-manager-console", "Manager console"],
      ["02-mobile-visits", "Mobile — today's visits", "portrait"],
      ["03-mobile-stock-report", "Mobile — stock report", "portrait"],
      ["04-mobile-checklist", "Mobile — visit checklist", "portrait"],
      ["05-mobile-reports", "Mobile — reports", "portrait"],
      ["06-compliance", "Compliance"],
    ]),
  },
  {
    slug: "vibecheck",
    title: "VibeCheck",
    industry: "Content / Social",
    category: "Portfolio",
    status: "Portfolio project",
    tagline: "A mood-based blogging app with custom markdown rendering.",
    overview:
      "VibeCheck is a mood-based blogging application with custom markdown rendering and a React Reducer-driven state architecture, built to manage multi-layered application state across drafts, published posts, moods and reactions.",
    features: [
      "Custom markdown editor and renderer for post content",
      "Mood tagging so posts can be browsed and filtered by tone",
      "Draft and publish workflow with post status tracking",
      "Reaction and comment counts surfaced on the post feed",
      "React Reducer-based state management across the multi-layered app state",
    ],
    contributions: [
      "Built the markdown editor and renderer from scratch in React",
      "Designed the Reducer-based state architecture for posts, drafts and reactions",
      "Implemented the Express.js API for posts, moods and reactions",
    ],
    stack: ["React", "Node.js", "Express.js", "JavaScript"],
    skills: ["Custom markdown rendering", "Reducer state architecture", "Express.js API design"],
    accent: "purple",
    caseStudyPdf: "/docs/vibecheck-case-study.pdf",
    images: screens("vibecheck", "VibeCheck", [
      ["01-feed", "Public feed"],
      ["02-markdown-editor", "Markdown editor"],
      ["03-post-detail", "Post detail"],
      ["04-mood-explorer", "Mood explorer"],
      ["05-author-profile", "Author profile"],
      ["06-notifications", "Notifications"],
    ]),
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);

export const featuredProjects = projects.filter((p) => p.featured);

export function getAdjacentProjects(slug: string) {
  const i = projects.findIndex((p) => p.slug === slug);
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
  };
}
