import type { Project, ProjectImage } from "@/types/content";

/** Build image entries from `/public/projects/<slug>/<file>.webp`. */
function screens(
  slug: string,
  title: string,
  items: [file: string, caption: string, orientation?: "portrait"][],
): ProjectImage[] {
  return items.map(([file, caption, orientation]) => ({
    src: `/projects/${slug}/${file}.webp`,
    alt: `${title} — ${caption} screen`,
    caption,
    orientation: orientation ?? "landscape",
  }));
}

export const projects: Project[] = [
  {
    slug: "gerko",
    title: "Gerko",
    industry: "HealthTech SaaS",
    category: "Professional",
    role: "Full-Stack Engineer · reports to CTO",
    status: "Live · company product",
    tagline:
      "All-in-one practice management software for health practitioners — scheduling, patient records, billing, reviews and an AI medical scribe.",
    overview:
      "Gerko is a multi-tenant practice management SaaS used by clinics across 15+ health professions, from physiotherapy and psychology to chiropractic and nutrition. Practices run online booking, SMS and email reminders, clinical notes, invoicing, insurance claims, review automation and reporting from one platform, with each clinic's patient data kept strictly segregated. As a Full-Stack Engineer reporting directly to the CTO, I lead feature delivery end to end across the React front end and the Node.js / PostgreSQL back end, and mentor a team of three junior developers.",
    features: [
      "Smart scheduling with 24/7 online booking, SMS & email reminders and calendar integrations",
      "Multi-tenant architecture with segregated patient databases and role-based permissions",
      "Clinical notes with templates, voice-to-text and full edit history",
      "AI-powered medical scribe that turns consultations into structured clinical notes",
      "Invoicing, insurance claims and payment tracking with automated follow-ups",
      "Review automation, bulk SMS / email campaigns and practice analytics dashboards",
    ],
    contributions: [
      "Spearheaded end-to-end development of core product features across React, Node.js, Express.js and PostgreSQL",
      "Designed and maintain the reusable React component library (Webpack + Jest) used across the product — +20% development velocity",
      "Led telemetry-driven Core Web Vitals work that cut initial page load times by 35% and improved SEO",
      "Built secure, high-throughput REST APIs and microservices for real-time sync across segregated patient databases",
      "Introduced automated component and integration testing, reducing production regressions by 15%",
      "Mentor 3 junior developers through code review, pairing and Git / testing best practices",
    ],
    stack: ["React", "TypeScript", "Node.js", "Express.js", "PostgreSQL", "Webpack", "Jest", "REST APIs"],
    skills: [
      "Multi-tenant SaaS architecture",
      "Performance & Core Web Vitals",
      "Component libraries",
      "API & microservice design",
      "Technical leadership",
    ],
    metrics: [
      { value: "35%", label: "faster initial page load" },
      { value: "20%", label: "higher development velocity" },
      { value: "15%", label: "fewer production regressions" },
      { value: "15+", label: "health professions served" },
    ],
    accent: "blue",
    featured: true,
    liveUrl: "https://app.gerko.io",
    images: screens("gerko", "Gerko", [
      ["01-home", "Product website"],
      ["02-dashboard", "Practice analytics dashboard"],
      ["03-pricing", "Multi-currency pricing"],
      ["04-professions", "Professions served"],
    ]),
  },
  {
    slug: "lwazi-hair",
    title: "Lwazi Hair",
    industry: "E-commerce / Shopify",
    category: "Client",
    role: "Full-Stack Developer · sole developer",
    status: "Live · client project",
    tagline:
      "A live Shopify store for a South African human-hair and wig retailer — with a custom wig & bundle builder, live pricing and real orders.",
    overview:
      'Designed and built the full Shopify storefront for Lwazi Hair, a human-hair and wig retailer trading online, retail and wholesale. Beyond a standard theme, the store runs a custom multi-step "Build Your Wig" and bundle builder: customers pick a collection, texture, closure, length and colour, see the price update live at every step, preview the length, and get an auto-generated product code before adding to cart. Checkout runs through Yoco card and EFT payments, deliveries are tracked through The Courier Guy, and a one-tap WhatsApp flow handles enquiries.',
    features: [
      "4-step custom wig builder — collection, texture, closure type, length and colour — across 6 wig collections",
      'Bundle builder across 7 bundle classes with per-length pricing (8" to 30") and colour options',
      "Live price recalculation and length preview at every step, with add-ons like professional customisation",
      "Auto-generated product codes (e.g. HB-BR-BW-12-G3-BLK-C) so every custom order is fulfilled exactly as configured",
      "Saved selections — returning customers are welcomed back and can continue a half-built wig where they left off",
      'Cart reservation confirmation modal to reduce checkout drop-off, plus "add another" multi-item flows',
      "WhatsApp order hand-off that sends the full configuration, product code and total as a ready-to-confirm message",
      "Secure Yoco card & EFT checkout, Courier Guy order tracking and one-tap WhatsApp support",
    ],
    contributions: [
      "Designed and built the complete storefront, navigation and theme customisations in Liquid and JavaScript",
      "Engineered the wig and bundle builders: step state, pricing matrices, length preview and product-code generation",
      "Integrated Yoco payments, The Courier Guy tracking page and the WhatsApp Business ordering flow",
      "Merchandised and structured 85+ products across wigs, bundles, closures and frontals for discoverability",
      'Handled on-page SEO and the Google Business listing so the store shows up for "human hair wigs South Africa" searches',
    ],
    stack: ["Shopify", "Liquid", "JavaScript", "Yoco Payments", "WhatsApp Business", "The Courier Guy"],
    skills: [
      "E-commerce UX",
      "Product configurators",
      "State persistence",
      "SEO",
      "Dynamic pricing logic",
      "Payments integration",
      "Client delivery",
    ],
    metrics: [
      { value: "85+", label: "products merchandised" },
      { value: "6", label: "custom wig collections" },
      { value: "7", label: "bundle classes with live pricing" },
      { value: "5.0★", label: "Google Business rating" },
    ],
    accent: "amber",
    featured: true,
    liveUrl: "https://lwazihair.co.za",
    images: [
      ...screens("lwazi-hair", "Lwazi Hair", [
        ["01-home", "Storefront home"],
        ["02-product-grid", "Product catalogue"],
        ["03-product-detail", "Product detail"],
        ["04-collections", "Personalise your hair — collections"],
        ["05-wig-builder", "Build Your Wig — choose a collection"],
        ["06-wig-options", "Wig builder — texture, closure, length & colour"],
        ["07-bundle-builder", "Bundle builder with length preview"],
        ["08-cart-reserved", "Cart reservation confirmation"],
        ["09-order-summary", "Live order summary & product code", "portrait"],
        ["10-length-preview", "Length preview", "portrait"],
        ["11-bundle-summary", "Bundle order summary", "portrait"],
        ["12-checkout", "Checkout summary"],
        ["13-saved-selection", "Saved selection — welcome back"],
        ["14-whatsapp-order", "WhatsApp order with product code", "portrait"],
        ["15-google-search", "Google search listing"],
        ["16-google-business", "Google Business profile"],
      ]),
    ],
  },
  {
    slug: "financeflow",
    title: "FinanceFlow",
    industry: "Financial Services",
    category: "Portfolio",
    status: "Live project",
    tagline: "A secure, responsive dashboard for accounts, transfers and reporting.",
    overview:
      "FinanceFlow is a responsive financial services dashboard for account balances, transaction history, transfers, and beneficiary management. It was built around secure authentication flows, idempotent transaction requests, defensive error handling, and an audit trail, so customers and support staff can trust every balance and transfer shown on screen.",
    features: [
      "Real-time account balance and transaction history views with drill-down detail",
      "Money transfer workflow with beneficiary management and confirmation steps",
      "Idempotent transaction requests to prevent duplicate transfers on retry or network failure",
      "Form validation and defensive error handling across every money-movement flow",
      "Audit event log for transfers and account changes to support compliance reviews",
      "API-driven reporting views for account activity, exportable for reconciliation",
    ],
    contributions: [
      "Designed the React/TypeScript front end and the Next.js routing and data-fetching layer",
      "Built the Node.js REST API and PostgreSQL schema for accounts, transfers and audit events",
      "Implemented idempotency keys and validation on the transfer endpoints to protect data integrity",
      "Set up GitHub Actions for linting, automated tests and CI checks on every pull request",
    ],
    stack: ["React", "TypeScript", "Next.js", "Node.js", "PostgreSQL", "Tailwind CSS", "GitHub Actions"],
    skills: ["Secure authentication", "REST API design", "PostgreSQL schema design", "CI/CD", "Form validation"],
    accent: "blue",
    featured: true,
    caseStudyPdf: "/docs/financeflow-case-study.pdf",
    images: screens("financeflow", "FinanceFlow", [
      ["01-overview", "Overview"],
      ["02-transactions", "Transactions"],
      ["03-new-transfer", "New transfer"],
      ["04-audit-log", "Audit log"],
      ["05-beneficiaries", "Beneficiaries"],
      ["06-reports", "Reports"],
    ]),
  },
  {
    slug: "shopsphere",
    title: "ShopSphere",
    industry: "E-commerce",
    category: "Portfolio",
    status: "Live project",
    tagline: "A full-stack storefront with catalogue, cart and order management.",
    overview:
      "ShopSphere is a full-stack commerce application covering the product catalogue, search and filtering, cart management, checkout, customer accounts and order history. The interface is mobile-first and the backend exposes inventory-aware APIs so stock levels stay accurate across browsing, checkout and fulfilment.",
    features: [
      "Product catalogue with search, category filters and sort options",
      "Cart and multi-step checkout workflow with order summary and validation",
      "Customer account area with saved addresses and order history",
      "Inventory-aware APIs that keep stock counts accurate through checkout",
      "Responsive, mobile-first layouts across catalogue, product and checkout pages",
      "Deployed on Vercel with a MongoDB-backed product and order data model",
    ],
    contributions: [
      "Built the catalogue, product detail and checkout flows in React/Next.js and TypeScript",
      "Designed the MongoDB schema for products, inventory, carts and orders",
      "Implemented the Node.js order and inventory APIs, including stock-decrement logic",
      "Tuned layouts and Tailwind CSS breakpoints for a mobile-first shopping experience",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "MongoDB", "Tailwind CSS", "Vercel"],
    skills: ["E-commerce UX", "MongoDB data modelling", "API design", "Mobile-first UI"],
    accent: "amber",
    caseStudyPdf: "/docs/shopsphere-case-study.pdf",
    images: screens("shopsphere", "ShopSphere", [
      ["01-storefront", "Storefront"],
      ["02-product-detail", "Product detail"],
      ["03-cart-checkout", "Cart & checkout"],
      ["04-order-history", "Order history"],
      ["05-search-filters", "Search & filters"],
      ["06-order-confirmation", "Order confirmation"],
    ]),
  },
  {
    slug: "fleetflow",
    title: "FleetFlow",
    industry: "Logistics & Field Ops",
    category: "Portfolio",
    status: "Live project",
    tagline: "A live operations dashboard for dispatch, field workers and tasks.",
    overview:
      "FleetFlow is an operations dashboard for dispatching work, tracking driver and field-worker activity, and monitoring task status in real time. Location updates and status changes stream over WebSockets so dispatchers always see current, not stale, field data.",
    features: [
      "Live dispatch board for assigning tasks to drivers and field workers",
      "Real-time location and status updates over WebSockets",
      "Task status tracking from assigned through in-progress to completed",
      "Operational reporting on completion rates and response times",
      "Map-oriented views for field-worker location and route context",
    ],
    contributions: [
      "Built the real-time dispatch UI in React/TypeScript with live WebSocket updates",
      "Designed the PostgreSQL schema for tasks, drivers and status history",
      "Implemented the Node.js WebSocket layer for location and status broadcast",
      "Deployed the service on AWS and set up monitoring for the real-time connections",
    ],
    stack: ["React", "TypeScript", "Node.js", "PostgreSQL", "WebSockets", "AWS"],
    skills: ["Real-time systems", "Operational dashboards", "PostgreSQL", "AWS deployment"],
    accent: "cyan",
    caseStudyPdf: "/docs/fleetflow-case-study.pdf",
    images: screens("fleetflow", "FleetFlow", [
      ["01-live-map", "Live dispatch map"],
      ["02-task-board", "Task board"],
      ["03-drivers", "Drivers"],
      ["04-task-detail", "Task detail"],
      ["05-reports", "Reports"],
      ["06-new-task", "New task"],
    ]),
  },
  {
    slug: "learnhub",
    title: "LearnHub",
    industry: "Education / EdTech",
    category: "Portfolio",
    status: "Live project",
    tagline: "A learning platform for courses, progress tracking and assessments.",
    overview:
      "LearnHub is a learning platform covering course discovery, lessons, progress tracking, assessments and learner dashboards, alongside instructor tools for managing content. The interface was built with accessibility and responsiveness as first-class requirements.",
    features: [
      "Course discovery and enrolment with category and level filtering",
      "Lesson player with progress tracking across modules",
      "Assessments and quizzes with score history",
      "Learner dashboard summarising progress across active courses",
      "Instructor content-management views for courses and lessons",
      "Accessibility-focused, responsive layouts throughout",
    ],
    contributions: [
      "Built the learner and instructor dashboards in React/Next.js and TypeScript",
      "Designed the PostgreSQL schema for courses, lessons, enrolments and progress",
      "Implemented progress-tracking and assessment-scoring APIs in Node.js",
      "Audited and improved keyboard navigation and accessibility across key flows",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
    skills: ["Accessibility (a11y)", "Progress-tracking systems", "PostgreSQL", "Responsive UI"],
    accent: "green",
    caseStudyPdf: "/docs/learnhub-case-study.pdf",
    images: screens("learnhub", "LearnHub", [
      ["01-catalogue", "Course catalogue"],
      ["02-lesson-player", "Lesson player"],
      ["03-learner-dashboard", "Learner dashboard"],
      ["04-learners", "Learners"],
      ["05-assessment", "Assessment"],
      ["06-course-landing", "Course landing page"],
    ]),
  },
  {
    slug: "propmanage",
    title: "PropManage",
    industry: "Real Estate / PropTech",
    category: "Portfolio",
    status: "Live project",
    tagline: "A property management app for listings, tenants and maintenance.",
    overview:
      "PropManage is a property management application for listings, tenant records, maintenance requests and document workflows. Role-based access keeps agents, property managers and administrators scoped to the data relevant to their role.",
    features: [
      "Property listing management with search and filtering",
      "Tenant records and lease tracking",
      "Maintenance request workflow from submission through resolution",
      "Document workflows for leases and inspection reports",
      "Role-based access control across agents, managers and admins",
      "Dashboards summarising occupancy and open maintenance items",
    ],
    contributions: [
      "Built the listings, tenant and maintenance-request UIs in React/TypeScript",
      "Designed the Express.js REST API and MongoDB schema for properties, leases and tickets",
      "Implemented role-based access control across the API and front end",
      "Set up document upload and storage workflows on AWS",
    ],
    stack: ["React", "TypeScript", "Node.js", "Express.js", "MongoDB", "AWS"],
    skills: ["Role-based access control", "Express.js API design", "MongoDB", "AWS document storage"],
    accent: "purple",
    caseStudyPdf: "/docs/propmanage-case-study.pdf",
    images: screens("propmanage", "PropManage", [
      ["01-listings", "Listings grid"],
      ["02-property-detail", "Property detail"],
      ["03-maintenance", "Maintenance board"],
      ["04-tenants", "Tenants"],
      ["05-new-maintenance-request", "New maintenance request"],
      ["06-documents", "Documents"],
    ]),
  },
  {
    slug: "talenthub",
    title: "TalentHub",
    industry: "HR / People Ops",
    category: "Portfolio",
    status: "Live project",
    tagline: "A recruitment and employee-management workflow tool.",
    overview:
      "TalentHub is a recruitment and employee-management interface covering vacancies, candidate pipelines, interview scheduling, onboarding tasks and employee records, with permissioned access for HR, hiring managers and administrators.",
    features: [
      "Vacancy management with candidate pipeline stages",
      "Interview scheduling with calendar-style views",
      "Onboarding task checklists for new hires",
      "Employee records with permissioned, role-based visibility",
      "Workflow dashboards summarising pipeline health across open roles",
    ],
    contributions: [
      "Built the candidate pipeline and interview-scheduling UI in React/Next.js and TypeScript",
      "Designed the PostgreSQL schema for vacancies, candidates, interviews and onboarding tasks",
      "Implemented permissioned employee-record views in the Node.js API",
      "Configured GitHub Actions for automated testing and deployment checks",
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "GitHub Actions"],
    skills: ["Workflow / pipeline UI", "PostgreSQL schema design", "Access control", "CI/CD"],
    accent: "blue",
    caseStudyPdf: "/docs/talenthub-case-study.pdf",
    images: screens("talenthub", "TalentHub", [
      ["01-pipeline", "Candidate pipeline"],
      ["02-candidate-profile", "Candidate profile"],
      ["03-interview-calendar", "Interview calendar"],
      ["04-vacancies", "Vacancies"],
      ["05-new-vacancy", "New vacancy"],
      ["06-employees", "Employee directory"],
    ]),
  },
  {
    slug: "knights-nestle",
    title: "Knights-Nestle Management System",
    industry: "Retail Operations",
    category: "Portfolio",
    status: "Live project",
    tagline: "A merchandiser scheduling and stock-reporting tool for retail execution.",
    overview:
      "A full-stack retail execution application for scheduling and tracking distributed merchandiser workflows and stock reports, built with mobile-responsive React interfaces so field merchandisers can log visits and stock counts from any device.",
    features: [
      "Merchandiser visit scheduling across multiple retail stores",
      "In-store stock-report capture from mobile-responsive screens",
      "Visit status and stock-compliance tracking",
      "Manager-facing dashboards summarising visit and compliance rates",
    ],
    contributions: [
      "Built the merchandiser scheduling and stock-reporting UI in React",
      "Implemented the Node.js API for visit scheduling and stock-report submission",
      "Optimised layouts for in-store mobile use, since merchandisers work primarily on phones",
    ],
    stack: ["React", "Node.js", "Responsive UI"],
    skills: ["Mobile-responsive UI", "Field-operations tooling", "Node.js API design"],
    accent: "green",
    caseStudyPdf: "/docs/knights-nestle-case-study.pdf",
    images: screens("knights-nestle", "Knights-Nestle", [
      ["01-manager-console", "Manager console"],
      ["02-mobile-visits", "Mobile — today's visits", "portrait"],
      ["03-mobile-stock-report", "Mobile — stock report", "portrait"],
      ["04-mobile-checklist", "Mobile — visit checklist", "portrait"],
      ["05-mobile-reports", "Mobile — reports", "portrait"],
      ["06-compliance", "Compliance"],
    ]),
  },
  {
    slug: "vibecheck",
    title: "VibeCheck",
    industry: "Content / Social",
    category: "Portfolio",
    status: "Live project",
    tagline: "A mood-based blogging app with custom markdown rendering.",
    overview:
      "VibeCheck is a mood-based blogging application with custom markdown rendering and a React Reducer-driven state architecture, built to manage multi-layered application state across drafts, published posts, moods and reactions.",
    features: [
      "Custom markdown editor and renderer for post content",
      "Mood tagging so posts can be browsed and filtered by tone",
      "Draft and publish workflow with post status tracking",
      "Reaction and comment counts surfaced on the post feed",
      "React Reducer-based state management across the multi-layered app state",
    ],
    contributions: [
      "Built the markdown editor and renderer from scratch in React",
      "Designed the Reducer-based state architecture for posts, drafts and reactions",
      "Implemented the Express.js API for posts, moods and reactions",
    ],
    stack: ["React", "Node.js", "Express.js", "JavaScript"],
    skills: ["Custom markdown rendering", "Reducer state architecture", "Express.js API design"],
    accent: "purple",
    caseStudyPdf: "/docs/vibecheck-case-study.pdf",
    images: screens("vibecheck", "VibeCheck", [
      ["01-feed", "Public feed"],
      ["02-markdown-editor", "Markdown editor"],
      ["03-post-detail", "Post detail"],
      ["04-mood-explorer", "Mood explorer"],
      ["05-author-profile", "Author profile"],
      ["06-notifications", "Notifications"],
    ]),
  },
];

export const getProject = (slug: string) => projects.find((p) => p.slug === slug);

export const featuredProjects = projects.filter((p) => p.featured);

export function getAdjacentProjects(slug: string) {
  const i = projects.findIndex((p) => p.slug === slug);
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
  };
}
